FROM mcr.microsoft.com/dotnet/runtime:9.0 AS base
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["DummyWorkflowJob/DummyWorkflowJob.csproj", "DummyWorkflowJob/"]
RUN dotnet restore "DummyWorkflowJob/DummyWorkflowJob.csproj"
COPY . .
WORKDIR "/src/DummyWorkflowJob"
RUN dotnet build "DummyWorkflowJob.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "DummyWorkflowJob.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DummyWorkflowJob.dll"]
